export const fakeData = [
  {
    origin_board_idx: 1,
    board_idx: 1,
    board_title: 'First Board',
    board_desc: 'First Description',
    origin_list_idx: 1,
    list_idx: 1,
    list_title: 'First_First List',
    origin_card_idx: 1,
    card_title: 'First cardTitle',
    card_desc: 'a',
    is_private: 0,
    deadline: null,
    order: null,
    assignee_id: 0,
    owner_idx: 8
  },
  {
    origin_board_idx: 1,
    board_idx: 1,
    board_title: 'First Board',
    board_desc: 'First Description',
    origin_list_idx: 1,
    list_idx: 1,
    list_title: 'First_First List',
    origin_card_idx: 11,
    card_title: 'First cardTitle',
    card_desc: 'eroeorititiutiri',
    is_private: 0,
    deadline: null,
    order: null,
    assignee_id: 0,
    owner_idx: 8
  },
  {
    origin_board_idx: 1,
    board_idx: 1,
    board_title: 'First Board',
    board_desc: 'First Description',
    origin_list_idx: 1,
    list_idx: 1,
    list_title: 'First_First List',
    origin_card_idx: 2,
    card_title: 'First cardTitle',
    card_desc: 'asdfv',
    is_private: 0,
    deadline: null,
    order: null,
    assignee_id: 0,
    owner_idx: 8
  },
  {
    origin_board_idx: 1,
    board_idx: 1,
    board_title: 'First Board',
    board_desc: 'First Description',
    origin_list_idx: 1,
    list_idx: 2,
    list_title: 'First_Second List',
    origin_card_idx: 1,
    card_title: 'CardTitle',
    card_desc: 'b',
    is_private: 0,
    deadline: null,
    order: null,
    assignee_id: 0,
    owner_idx: 8
  },
  {
    origin_board_idx: 2,
    board_idx: 2,
    board_title: 'Second Board',
    board_desc: 'Second Description',
    origin_list_idx: 1,
    list_idx: 1,
    list_title: 'Second_First List',
    origin_card_idx: 1,
    card_title: 'cardTitle',
    card_desc: 'c',
    is_private: 0,
    deadline: null,
    order: null,
    assignee_id: 0,
    owner_idx: 8
  },
  {
    origin_board_idx: 3,
    board_idx: 3,
    board_title: 'T_frist Board',
    board_desc: 'T_first Description',
    origin_list_idx: 1,
    list_idx: 1,
    list_title: 'T_First List',
    origin_card_idx: 1,
    card_title: 'cardTitle',
    card_desc: 'd',
    is_private: 1,
    deadline: null,
    order: null,
    assignee_id: 0,
    owner_idx: 8
  },
  {
    origin_board_idx: 4,
    board_idx: 4,
    board_title: 'T_Second Board',
    board_desc: 'T_Second Description',
    origin_list_idx: 10,
    list_idx: 7,
    list_title: 'T_First List',
    origin_card_idx: 1,
    card_title: 'cardTitle',
    card_desc: 'e',
    is_private: 1,
    deadline: null,
    order: null,
    assignee_id: 0,
    owner_idx: 8
  }
]
